version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: mancaperros_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: mancaperros_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3100:3100"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      SECRET_KEY: f4c961b34a2764b39914debb0b91c22664a44cf16094515f58ef88256291e5fe
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 3100 --reload # Comment in prod

volumes:
  mysql_data:
