"""Add routine_group_order field to Exercise_plan

Revision ID: 0e72225126e6
Revises: 58787050df92
Create Date: 2025-01-20 19:17:14.591331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e72225126e6'
down_revision = '58787050df92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_plans', sa.Column('routine_group_order', sa.JSON(), nullable=False, server_default='["chest", "back", "shoulders", "legs"]'))
    op.add_column('exercise_plans_global', sa.Column('routine_group_order', sa.JSON(), nullable=False, server_default='["chest", "back", "shoulders", "legs"]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_plans_global', 'routine_group_order')
    op.drop_column('exercise_plans', 'routine_group_order')
    # ### end Alembic commands ###
