"""Update User_Tracker model

Revision ID: 58787050df92
Revises: 9cfbf8dd7525
Create Date: 2025-01-09 17:01:49.793315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58787050df92'
down_revision = '9cfbf8dd7525'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tracker', sa.Column('push_time_increment', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users_tracker', sa.Column('pull_time_increment', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users_tracker', sa.Column('isometric_time_increment', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users_tracker', 'push_increment_units')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tracker', sa.Column('push_increment_units', sa.String(), nullable=False, server_default='uds'))
    op.drop_column('users_tracker', 'push_time_increment')
    op.drop_column('users_tracker', 'pull_time_increment')
    op.drop_column('users_tracker', 'isometric_time_increment')
    # ### end Alembic commands ###
