"""Add additional database indexes

Revision ID: a2b3c4d5e6f7
Revises: f1a2b3c4d5e6
Create Date: 2026-01-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b3c4d5e6f7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add additional indexes for performance optimization

    # Tabla exercise_plans: Add index on exercise_plan_type for filtering by type
    op.create_index('idx_exercise_plans_type', 'exercise_plans', ['exercise_plan_type'], unique=False)

    # Tabla rutines: Add composite index for queries filtering by plan and group
    op.create_index('idx_rutines_plan_group', 'rutines', ['exercise_plan_id', 'rutine_group'], unique=False)

    # Tabla user_tracker: Add composite index for queries filtering by user and info type
    op.create_index('idx_user_tracker_user_type', 'user_tracker', ['user_id', 'info_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes in reverse order
    op.drop_index('idx_user_tracker_user_type', table_name='user_tracker')
    op.drop_index('idx_rutines_plan_group', table_name='rutines')
    op.drop_index('idx_exercise_plans_type', table_name='exercise_plans')
    # ### end Alembic commands ###
