"""Add database indexes

Revision ID: f1a2b3c4d5e6
Revises: 0e72225126e6
Create Date: 2026-01-10 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '0e72225126e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes for performance optimization
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_user_name', 'users', ['user_name'], unique=False)
    op.create_index('idx_exercise_plans_user_owner_id', 'exercise_plans', ['user_owner_id'], unique=False)
    op.create_index('idx_rutines_exercise_plan_id', 'rutines', ['exercise_plan_id'], unique=False)
    op.create_index('idx_exercises_rutine_id', 'exercises', ['rutine_id'], unique=False)
    op.create_index('idx_user_tracker_user_id', 'user_tracker', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes in reverse order
    op.drop_index('idx_user_tracker_user_id', table_name='user_tracker')
    op.drop_index('idx_exercises_rutine_id', table_name='exercises')
    op.drop_index('idx_rutines_exercise_plan_id', table_name='rutines')
    op.drop_index('idx_exercise_plans_user_owner_id', table_name='exercise_plans')
    op.drop_index('idx_users_user_name', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    # ### end Alembic commands ###
